name: wayland
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

# Cancel active CI runs for a PR before starting another run
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash --noprofile --norc -x -e -o pipefail {0}

env:
  FORCE_COLOR: "1"

jobs:
  wayland:
    name: wayland
    runs-on: ubuntu-24.04
    steps:

    - name: Checkout
      uses: actions/checkout@v4.1.6
      with:
        fetch-depth: 0
        repository: beeware/toga

    - name: Install Briefcase
      env:
        PIP_BREAK_SYSTEM_PACKAGES: 1
        PIP_IGNORE_INSTALLED: 1
      run: python -m pip install briefcase

    - name: Install Dependencies
      run: |
        sudo apt update
        #sudo apt install -y sway libwayland-dev wayland-utils  # weston libwayland-client0 libwayland-server0 libglx-mesa0 libegl1 mesa-utils-extra
        sudo apt install -y mutter
        sudo apt install -y pkg-config python3-dev libgirepository1.0-dev libcairo2-dev gir1.2-webkit2-4.1 libjpeg-dev

    - name: Wayland
      env:
        WLR_BACKENDS: headless
      run: |
        #sudo weston --backends
        #sudo weston --no-config --socket=wayland-1 --width 2048 --height 1536 --backend headless &
        #sway -d -V &
        
        Xvfb :99 -screen 0 2048x1536x24 &
        sleep 1
        DISPLAY=:99 mutter --nested --wayland --no-x11 --wayland-display toga &
        
        sleep 1
    
    - name: Run app
      env:
        WAYLAND_DISPLAY: toga
      working-directory: testbed
      run: briefcase run --test

